import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Features from "../components/index/Features";
import Gallery from "../components/index/Gallery";
import welcomeImg from "../public/assets/tractor12.jpg";
import whyImg from "../public/assets/agric06.jpg";
import dummyData from "../dummyData";
import Products from "../components/index/Products";
import { CheckCircleIcon } from "@heroicons/react/24/solid";

export default function Home({
	featuredData,
	productTitle,
	productContent,
	galleryContent,
	isFooter,
}) {
	return (
		<div className="">
			<Head>
				<title>Bunkasa - Crops and Machines</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Landing Section */}
			<div className="flex flex-col font-bold bg-bgImg bg-cover text-center justify-center h-screen">
				<h1 className="text-5xl mb-3">
					Crops <span className="text-green-900">&</span> Machines
				</h1>
				<h3 className="">
					Bringing <span className="text-green-900">The </span>
					Best <span className="text-green-900">of</span> Agriculture
				</h3>
				<div className="pt-10">
					<Link
						href="/services"
						className="bg-headerGreen px-10 py-4 border rounded-full hover:border-2"
					>
						Services
					</Link>
				</div>
			</div>

			{/* Welcome Section */}
			<div className="flex flex-col lg:flex-row text-gray-500 h-screen py-4 lg:h-full lg:py-20">
				<div className="flex h-2/5 w-11/12 lg:h-full lg:w-1/2 self-center lg:justify-center">
					<Image
						src={welcomeImg}
						alt=""
						className="h-full w-full lg:h-1/2 lg:w-11/12 rounded-3xl"
					/>
				</div>
				<div className="flex flex-col px-4 py-4 h-3/5 lg:w-1/2 lg:justify-center">
					<div className="py-2">
						<h1 className="text-3xl lg:w-80">Welcome to Crops and Machines</h1>
						<h2 className="text-xl lg:w-40">Know Agriculture at Its Best </h2>
					</div>
					<p className="text-sm leading-6">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam
						maiores ad perferendis aspernatur nostrum autem quae, laborum
						quisquam, assumenda vel nulla, provident nam commodi veniam
						perspiciatis ipsum odit? Mollitia, nihil. Lorem ipsum dolor sit,
						amet consectetur adipisicing elit. Aliquam maiores ad perferendis
						aspernatur nostrum autem quae, laborum quisquam, assumenda vel
						nulla, provident nam commodi veniam perspiciatis ipsum odit?
						Mollitia, nihil.
					</p>
					<div className="pt-4 w-full">
						<Link href="">
							<h1 className="w-fit px-4 py-2 text-white bg-headerGreen hover:bg-white hover:text-headerGreen hover:border-2 hover:border-headerGreen">
								Learn More
							</h1>
						</Link>
					</div>
				</div>
			</div>

			{/* Featured Section */}
			<div className="text-gray-500 h-full border py-10 bg-lime-50">
				<div className="flex flex-col justify-center text-center px-10 h-60">
					<div className="">
						<h1 className="text-3xl">{featuredData.header.title}</h1>
					</div>
					<div className="pt-4 px-8">
						<p className="text-sm">{featuredData.header.desc}</p>
					</div>
				</div>
				<div className="">
					<Features features={featuredData.content} />
				</div>
			</div>

			{/* Products Section */}
			<div className="flex flex-col text-gray-500 h-full border pb-10">
				<div className="flex flex-col justify-center text-center px-10 py-20 sm:px-0">
					<div className="">
						<h1 className="text-3xl">{productTitle.title}</h1>
					</div>
					<div className="pt-4 px-8">
						<p className="text-sm">{productTitle.desc}</p>
					</div>
				</div>
				<div className="">
					<Products products={productContent} />
				</div>
			</div>

			{/* Why Choose Us Section */}
			<div className="flex flex-col lg:flex-row text-gray-500 h-full py-4 lg:h-full lg:py-20">
				<div className="flex h-2/5 w-11/12 lg:h-full lg:w-1/2 self-center lg:justify-center">
					<Image
						src={whyImg}
						alt=""
						className="h-full w-full lg:h-1/2 lg:w-11/12 rounded-3xl"
					/>
				</div>
				<div className="flex flex-col px-4 py-4 h-3/5 lg:w-1/2 lg:justify-center">
					<div className="py-2">
						<h1 className="text-3xl lg:w-80">Why Choose Us</h1>
						<p className="text-sm leading-6">
							Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam
							maiores ad perferendis aspernatur nostrum autem quae, laborum
							quisquam.
						</p>
					</div>
					<div className="pt-4 w-full h-full">
						<div className="flex w-full">
							<CheckCircleIcon className="text-headerGreen" height={50} />
							<div className="flex flex-col w-full pl-8">
								<h1 className="text-xl lg:w-80">Natural Products</h1>
								<p className="text-sm leading-6">
									Lorem ipsum dolor sit, amet consectetur adipisicing elit.
									Aliquam maiores ad perferendis aspernatur nostrum autem quae,
									laborum quisquam.
								</p>
							</div>
						</div>
						<div className="flex w-full pt-4">
							<CheckCircleIcon className="text-headerGreen" height={50} />
							<div className="flex flex-col w-full pl-8">
								<h1 className="text-xl lg:w-80">100% Mechanical Equipments</h1>
								<p className="text-sm leading-6">
									Lorem ipsum dolor sit, amet consectetur adipisicing elit.
									Aliquam maiores ad perferendis aspernatur nostrum autem quae,
									laborum quisquam.
								</p>
							</div>
						</div>
						<div className="flex w-full pt-4">
							<CheckCircleIcon className="text-headerGreen" height={50} />
							<div className="flex flex-col w-full pl-8">
								<h1 className="text-xl lg:w-80">Natural Products</h1>
								<p className="text-sm leading-6">
									Lorem ipsum dolor sit, amet consectetur adipisicing elit.
									Aliquam maiores ad perferendis aspernatur nostrum autem quae,
									laborum quisquam.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>

			{/* Gallery Section */}
			<div className="text-gray-500 h-full border py-10 bg-lime-50">
				<div className="flex flex-col justify-center text-center px-10 h-60">
					<div className="">
						<h1 className="text-3xl">{galleryContent.header.title}</h1>
					</div>
					<div className="pt-4 px-8">
						<p className="text-sm">{galleryContent.header.desc}</p>
					</div>
				</div>
				<div className="">
					<Gallery gallery={galleryContent.content} />
				</div>
			</div>
		</div>
	);
}

export function getServerSideProps() {
	const request = dummyData;

	return {
		props: {
			featuredData: request.featuredData,
			productTitle: request.productData.header,
			productContent: request.productData.content,
			galleryContent: request.GalleryData,
		},
	};
}
