import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Features from "../components/Features";
import Gallery from "../components/Gallery";
import welcomeImg from "../public/assets/tractor12.jpg";
import whyImg from "../public/assets/agric06.jpg";
import logoImg from "../public/assets/logo.jpg";
import dummyData from "../dummyData";
import Products from "../components/Products";
import styles from "../styles/Home.module.css";
import { CheckCircleIcon } from "@heroicons/react/24/solid";
import {
	FaFacebookF,
	FaTwitter,
	FaWhatsapp,
	FaYoutube,
	FaPaperPlane,
	FaEnvelopeOpen,
	FaHeadphones,
	FaLinkedinIn,
} from "react-icons/fa";

export default function Home({
	featuredData,
	productTitle,
	productContent,
	galleryContent,
}) {
	return (
		<div className="">
			<Head>
				<title>Bunkasa - Crops and Machines</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex flex-col font-bold text-center justify-center h-screen sm:h-[80vh]">
				<h1 className="text-5xl mb-3">
					Crops <span className="text-green-900">&</span> Machines
				</h1>
				<h3 className="">
					Bringin <span className="text-green-900">The </span>
					of <span className="text-green-900">Best</span> Agriculture
				</h3>
				<div className="pt-10">
					<Link
						href="/services"
						className="bg-headerGreen px-10 py-4 border rounded-full hover:border-2"
					>
						Services
					</Link>
				</div>
			</div>
			<div className="flex flex-col lg:flex-row text-gray-500 h-screen py-4 lg:h-full lg:py-20">
				<div className="flex h-2/5 w-11/12 lg:h-full lg:w-1/2 self-center lg:justify-center">
					<Image
						src={welcomeImg}
						alt=""
						className="h-full w-full lg:h-1/2 lg:w-11/12 rounded-3xl"
					/>
				</div>
				<div className="flex flex-col px-4 py-4 h-3/5 lg:w-1/2 lg:justify-center">
					<div className="py-2">
						<h1 className="text-3xl lg:w-80">Welcome to Crops and Machines</h1>
						<h2 className="text-xl lg:w-40">Know Agriculture at Its Best </h2>
					</div>
					<p className="text-sm leading-6">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam
						maiores ad perferendis aspernatur nostrum autem quae, laborum
						quisquam, assumenda vel nulla, provident nam commodi veniam
						perspiciatis ipsum odit? Mollitia, nihil. Lorem ipsum dolor sit,
						amet consectetur adipisicing elit. Aliquam maiores ad perferendis
						aspernatur nostrum autem quae, laborum quisquam, assumenda vel
						nulla, provident nam commodi veniam perspiciatis ipsum odit?
						Mollitia, nihil.
					</p>
					<div className="pt-4 w-full">
						<Link href="">
							<h1 className="w-fit px-4 py-2 text-white bg-headerGreen hover:bg-white hover:text-headerGreen hover:border-2 hover:border-headerGreen">
								Learn More
							</h1>
						</Link>
					</div>
				</div>
			</div>

			<div className="text-gray-500 h-full border py-10 bg-lime-50">
				<div className="flex flex-col justify-center text-center px-10 h-60">
					<div className="">
						<h1 className="text-3xl">{featuredData.header.title}</h1>
					</div>
					<div className="pt-4 px-8">
						<p className="text-sm">{featuredData.header.desc}</p>
					</div>
				</div>
				<div className="">
					<Features features={featuredData.content} />
				</div>
			</div>

			<div className="flex flex-col text-gray-500 h-full border pb-10">
				<div className="flex flex-col justify-center text-center px-10 py-20 sm:px-0">
					<div className="">
						<h1 className="text-3xl">{productTitle.title}</h1>
					</div>
					<div className="pt-4 px-8">
						<p className="text-sm">{productTitle.desc}</p>
					</div>
				</div>
				<div className="">
					<Products products={productContent} />
				</div>
			</div>

			<div className="flex flex-col lg:flex-row text-gray-500 h-full py-4 lg:h-full lg:py-20">
				<div className="flex h-2/5 w-11/12 lg:h-full lg:w-1/2 self-center lg:justify-center">
					<Image
						src={whyImg}
						alt=""
						className="h-full w-full lg:h-1/2 lg:w-11/12 rounded-3xl"
					/>
				</div>
				<div className="flex flex-col px-4 py-4 h-3/5 lg:w-1/2 lg:justify-center">
					<div className="py-2">
						<h1 className="text-3xl lg:w-80">Why Choose Us</h1>
						<p className="text-sm leading-6">
							Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam
							maiores ad perferendis aspernatur nostrum autem quae, laborum
							quisquam.
						</p>
					</div>
					<div className="pt-4 w-full h-full">
						<div className="flex w-full">
							<CheckCircleIcon className="text-headerGreen" height={50} />
							<div className="flex flex-col w-full pl-8">
								<h1 className="text-xl lg:w-80">Natural Products</h1>
								<p className="text-sm leading-6">
									Lorem ipsum dolor sit, amet consectetur adipisicing elit.
									Aliquam maiores ad perferendis aspernatur nostrum autem quae,
									laborum quisquam.
								</p>
							</div>
						</div>
						<div className="flex w-full pt-4">
							<CheckCircleIcon className="text-headerGreen" height={50} />
							<div className="flex flex-col w-full pl-8">
								<h1 className="text-xl lg:w-80">100% Mechanical Equipments</h1>
								<p className="text-sm leading-6">
									Lorem ipsum dolor sit, amet consectetur adipisicing elit.
									Aliquam maiores ad perferendis aspernatur nostrum autem quae,
									laborum quisquam.
								</p>
							</div>
						</div>
						<div className="flex w-full pt-4">
							<CheckCircleIcon className="text-headerGreen" height={50} />
							<div className="flex flex-col w-full pl-8">
								<h1 className="text-xl lg:w-80">Natural Products</h1>
								<p className="text-sm leading-6">
									Lorem ipsum dolor sit, amet consectetur adipisicing elit.
									Aliquam maiores ad perferendis aspernatur nostrum autem quae,
									laborum quisquam.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div className="text-gray-500 h-full border py-10 bg-lime-50">
				<div className="flex flex-col justify-center text-center px-10 h-60">
					<div className="">
						<h1 className="text-3xl">{galleryContent.header.title}</h1>
					</div>
					<div className="pt-4 px-8">
						<p className="text-sm">{galleryContent.header.desc}</p>
					</div>
				</div>
				<div className="">
					<Gallery gallery={galleryContent.content} />
				</div>
			</div>

			<div className="flex bg-headerGreen h-96 w-full px-4 gap-12">
				<div className="w-1/4 h-full">
					<div className={`${styles.footerHeader}`}>
						<Image src={logoImg} alt="" width={100} height={100} />
					</div>
					<div className="mb-4 text-sm">
						<h2 className="leading-7">
							Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam
							maiores ad perferendis aspernatur nostrum autem quae, laborum
							quisquam, assumenda vel nulla, provident nam commodi veniam
							perspiciatis ipsum odit.
						</h2>
					</div>
					<div className="flex w-full justify-around">
						<Link
							href="/facebook"
							className={`${styles.footerHover} border rounded-xl p-2`}
						>
							<FaFacebookF className="w-full h-5" />
						</Link>
						<Link
							href="/twitter"
							className={`${styles.footerHover} border rounded-xl p-2`}
						>
							<FaTwitter className="w-full h-5" />
						</Link>
						<Link
							href="/linkedIn"
							className={`${styles.footerHover} border rounded-xl p-2`}
						>
							<FaLinkedinIn className="w-full h-5" />
						</Link>
						<Link
							href="/youtube"
							className={`${styles.footerHover} border rounded-xl p-2`}
						>
							<FaYoutube className="w-full h-5" />
						</Link>
						<Link
							href="/Whatsapp"
							className={`${styles.footerHover} border rounded-xl p-2`}
						>
							<FaWhatsapp className="w-full h-5" />
						</Link>
					</div>
				</div>
				<div className="w-1/4 h-full">
					<div className={`${styles.footerHeader}`}>
						<h1>Customer Support</h1>
					</div>
					<div className="leading-8 text-sm">
						<ul>
							<li>Help and Ordering</li>
							<li>Privacy and Policy</li>
							<li>Return & Cancellation</li>
							<li>Delevery Schedule</li>
							<li>Get a Call</li>
							<li>Online Enquiry</li>
						</ul>
					</div>
				</div>
				<div className="w-1/4">
					<div className={`${styles.footerHeader}`}>
						<h1>Contact Info</h1>
					</div>
					<div className="text-sm leading-10">
						<div className="flex items-center w-full leading-6">
							<FaPaperPlane className="h-5" />
							<h2 className="pl-2 cursor-pointer">
								Km 31, Kaduna / Abuja Expressway, Kaduna State
							</h2>
						</div>
						<div className="flex items-center w-full">
							<FaEnvelopeOpen className="h-5" />
							<span className="pl-2">cropsandmachines@gmail.com</span>
						</div>
						<div className="flex items-center w-full">
							<FaHeadphones className="h-5" />
							<span className="pl-2">+234 802 358 3974</span>
						</div>
					</div>
				</div>
				<div className="w-1/4">
					<div className={`${styles.footerHeader}`}>
						<h1>NewsLetters</h1>
					</div>
					<div className="text-sm">
						<div className="mb-4">
							<span>
								Enter Your Email and We Would Send You Latest Information Plans.
							</span>
						</div>
						<div className="flex flex-col ">
							<input
								type="text"
								placeholder="Enter Your Email"
								className="h-8 pl-2 mb-2"
							/>
							<button
								type="submit"
								className={`${styles.footerHover} border rounded-md h-12 font-bold w-32`}
							>
								Subscribe
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}

export function getServerSideProps() {
	const request = dummyData;

	return {
		props: {
			featuredData: request.featuredData,
			productTitle: request.productData.header,
			productContent: request.productData.content,
			galleryContent: request.GalleryData,
		},
	};
}
